<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
	<AssemblyName>Stickies</AssemblyName>
	<Version>1.0.0</Version>
	<ApplicationIcon>Assets\icon.ico</ApplicationIcon>	  
  </PropertyGroup>

  <ItemGroup>
  	<Resource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Locales\Lang.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Lang.resx</DependentUpon>
    </Compile>
    <Compile Update="Views\FontPickerWindow.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Locales\Lang.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Lang.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="ModernWpfUI" Version="1.0.0-rc.1" />
    <PackageReference Include="PixiEditor.ColorPicker" Version="3.4.2.3" />
    <PackageReference Include="SharpVectors" Version="1.8.6" />
  </ItemGroup>

</Project>
